server:
  port: 8077
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false
  enabled: true

mybatis:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #开启自动下划线格式转驼峰格式
  map-underscore-to-camel-case: true

